///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesLoadw = 'assets/images/loadw.gif';
  static const String imagesLogo = 'assets/images/ic_launcher.png';
  static const String imagesDay = 'assets/images/day.png';
  static const String imagesNight = 'assets/images/night.png';
  static const String imageUnknown =
      'https://icons.veryicon.com/png/o/weather/weather-icon-5/unknown-weather-1.png';
}
